### ISSUE TITLE
Bad interaction between `eth_feeHistory` and FTSO provider submissions

### ISSUE THREAD

**Issue by alexdupre** [flare-foundation/coreth#28]
With the introduction of AP3/EIP-1559 a couple of new RPC calls have been introduced to estimate the required gas price. One of them is `eth_feeHistory`, that is the call used by MetaMask to calculate the low/market/aggressive priority gas prices on EIP-1559 enabled chains.

FTSO providers are encouraged to use a higher gas price to prioritize their transactions, with the assumption that most of the gas is automatically refunded by the system.

When combined, the result is that the `eth_feeHistory` call can return very high priority fee values at the end/start of a price epoch, as if all recent transactions had to spend a lot of gas to be included in a block, while actually most of gas was refunded. This deceives MetaMask that proposes absurdly high (and unneeded) priority fees to send transactions, ruining all the advantages of the dynamic fees introduced in AP3.

A solution might be to ignore or to normalize the gas used by transactions sent to the PriceSubmitter, in order to have meaningful values returned by `eth_feeHistory`.

For reference, this is the MetaMask code: https://github.com/MetaMask/controllers/tree/main/src/gas

Example:

![image_2022-03-23_07-49-26](https://user-images.githubusercontent.com/3694371/159717164-b404b4fc-b78d-490e-852b-839c0d38d650.png)

**Comment by awfm9** [comment]
Fixed in #29, released as Flare `v0.6.1`.
