### ISSUE TITLE
Create default validators component

### ISSUE THREAD

**Issue by awfm9** [flare-foundation/coreth#49]
We should create a default validators component that returns the default validators by epoch, rather than only be chain ID. That way, we can reduce the number of default validators after a certain point, which in turn allows us to shut down a good number of nodes. Rather than running 20 validators, we can only run 5 and save a bunch of costs.

For context, if there would ever be an issue with rewards being awarded for one reward epoch, or if all FTSO data providers would unset their validators, we would fall back to the default validators again.

**Comment by emailtovamos** [comment]
>That way, we can reduce the number of default validators after a certain point, 

I didn't understand this part. How exactly it is not possible now and how it will be possible if we are able to get default validators by epoch?

**Comment by awfm9** [comment]
Done in #51.
